stages:
  - generate_data
workload_1_generate_data:
  tags:
    - shell
    - corona
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://lc.llnl.gov/gitlab
  stage: generate_data
  extends: .corona
  script:
    - ls
