stages:
- generate_data
.lc:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://lc.llnl.gov/gitlab
.corona:
  extends: .lc
  tags:
  - shell
  - corona
workload_1_generate_data:
  stage: generate_data
  extends: .corona
  script:
  - ls
