variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CUSTOM_CI_ENV_DIR: ''
  CUSTOM_CI_OUTPUT_DIR: /usr/workspace/haridev/gitlab-runner-outputs
  DLIO_BENCHMARK_REPO: ''
  DLIO_BENCHMARK_TAG: ''
  DFTRACER_REPO: ''
  ENV_NAME: ''
  PYTHON_MODULE: ''
  MPI_MODULE: ''
  GCC_MODULE: ''
  DATA_PATH: /p/lustre3/haridev/gitlab-runner-data/
  LOG_STORE_DIR: /p/lustre3/iopp/dftracer-traces-lfs
  CORES: '48'
  GPUS: '8'
  NODES: '1'
  WALLTIME: '60'
  QUEUE: pdebug
  MAX_NODES: '8'
  SYSTEM_NAME: corona
stages:
- generate_data
.lc:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://lc.llnl.gov/gitlab
.corona:
  extends: .lc
  tags:
  - shell
  - corona
workload_1_generate_data:
  stage: generate_data
  extends: .corona
  script:
  - ls
