variables: {}
stages:
- generate_data
- train
- compress_output
- create_directory
- move
- compact
- compress_final
- cleanup
include:
- project: lc-templates/id_tokens
  file: id_tokens.yml
- local: .gitlab/scripts/common.yml
bert_v100_1_generate_data:
  stage: generate_data
  extends: .corona
  script:
  - ls
  - source .gitlab/scripts/variables.sh
  - source .gitlab/scripts/pre.sh
  - which python; which dlio_benchmark;
  - if [ -d temp/bert_v100-1-1/ ]; then echo 'Directory temp/bert_v100-1-1/ already
    exists. Skipping data generation.'; else flux run -N 1 --tasks-per-node=1 -q q
    -t 1 --exclusive dlio_benchmark workload=bert_v100 ++workload.dataset.data_folder=temp/bert_v100-1-1//data
    ++workload.train.epochs=1 ++workload.output.folder=temp/bert_v100/1/20250326001147/generate
    ++workload.workflow.generate_data=True ++workload.workflow.train=False; fi
  - if [ -d temp/bert_v100-1-1/ ] && grep -i 'error' temp/bert_v100/1/20250326001147/generate/dlio.log;
    then echo 'Error found in dlio.log'; exit 1; fi
bert_v100_1_1_train:
  stage: train
  extends: .corona
  script:
  - source .gitlab/scripts/variables.sh
  - source .gitlab/scripts/pre.sh
  - which python; which dlio_benchmark;
  - flux run -N 1 --tasks-per-node=1 -q q -t 1 --exclusive dlio_benchmark workload=bert_v100
    ++workload.dataset.data_folder=temp/bert_v100-1-1//data ++workload.checkpoint.checkpoint_folder=temp/bert_v100-1-1//checkpoint
    ++workload.train.epochs=1 ++workload.output.folder=temp/bert_v100/1/20250326001147/train
    hydra.run.dir=temp/bert_v100/1/20250326001147/train ++workload.workflow.generate_data=False
    ++workload.workflow.train=True
  - if grep -i 'error' temp/bert_v100/1/20250326001147/train/dlio.log; then echo 'Error
    found in dlio.log'; exit 1; fi
  needs:
  - bert_v100_1_generate_data
  variables:
    DFTRACER_ENABLE: '1'
    DFTRACER_INC_METADATA: '1'
bert_v100_1_1_compress_output:
  stage: compress_output
  extends: .corona
  script:
  - source .gitlab/scripts/variables.sh
  - source .gitlab/scripts/pre.sh
  - which python; which dftracer_pgzip;
  - flux run -N 1 --tasks-per-node=1 -q q -t 1 --exclusive dftracer_pgzip -d temp/bert_v100/1/20250326001147/train
  - if find temp/bert_v100/1/20250326001147/train -type f -name '*.pfw' | grep -q
    .; then echo 'Uncompressed .pfw files found!'; exit 1; fi
  - if ! find temp/bert_v100/1/20250326001147/train -type f -name '*.pfw.gz' | grep
    -q .; then echo 'No compressed .pfw.gz files found!'; exit 1; fi
  needs:
  - bert_v100_1_1_train
bert_v100_1_1_move:
  stage: move
  extends: .corona
  script:
  - source .gitlab/scripts/variables.sh
  - source .gitlab/scripts/pre.sh
  - mkdir -p temp/v1.0.10.dev72/corona/bert_v100/nodes-1/20250326001147/RAW/
  - mv temp/bert_v100/1/20250326001147/train/*.pfw.gz temp/v1.0.10.dev72/corona/bert_v100/nodes-1/20250326001147/RAW/
  - mv temp/bert_v100/1/20250326001147/train/.hydra temp/v1.0.10.dev72/corona/bert_v100/nodes-1/20250326001147/
  - mv temp/bert_v100/1/20250326001147/train/dlio.log temp/v1.0.10.dev72/corona/bert_v100/nodes-1/20250326001147/
  needs:
  - bert_v100_1_1_compress_output
bert_v100_1_1_compact:
  stage: compact
  extends: .corona
  script:
  - source .gitlab/scripts/variables.sh
  - source .gitlab/scripts/pre.sh
  - which python; which dftracer_split;
  - cd temp/v1.0.10.dev72/corona/bert_v100/nodes-1/20250326001147
  - dftracer_split -d $PWD/RAW -o $PWD/COMPACT -s 1024 -n bert_v100
  - if ! find $PWD/COMPACT -type f -name '*.pfw.gz' | grep -q .; then echo 'No compacted
    .pfw.gz files found!'; exit 1; fi
  needs:
  - bert_v100_1_1_move
bert_v100_1_1_compress_final:
  stage: compress_final
  extends: .corona
  script:
  - source .gitlab/scripts/variables.sh
  - source .gitlab/scripts/pre.sh
  - cd temp/v1.0.10.dev72/corona/bert_v100/nodes-1/20250326001147
  - tar -czf RAW.tar.gz RAW
  - tar -czf COMPACT.tar.gz COMPACT
  needs:
  - bert_v100_1_1_compact
bert_v100_1_1_cleanup:
  stage: cleanup
  extends: .corona
  script:
  - module load mpifileutils
  - flux run -N 1 --tasks-per-node=1 -q q -t 1 --exclusive drm temp/bert_v100/1/20250326001147
  needs:
  - bert_v100_1_1_compress_final
create_directory_common:
  stage: create_directory
  extends: .corona
  script:
  - ls
  - source .gitlab/scripts/variables.sh
  - source .gitlab/scripts/pre.sh
  - ./.gitlab/scripts/create_log_dir.sh
  needs:
  - needs: bert_v100_1_1_compress_output
    optional: true
